spring:
  application:
    name: SERVICE-REGISTRY

server:
    port: 8761

#To disable eureka client behaviours
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/